name: workflow

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER REPOSITORY: ${{ secrets.DOCKER_HUB_USERNAME }}
      IMAGE_TAG: ${{ github.run_number }}
      BUILD_TOKEN: ${{ secrets.BUILD_TOKEN }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}
      -
        name: Build Docker image
        run:
          docker build . --file ./Dockerfile --tag $DOCKER_REPOSITORY/mock_gallery:$GITHUB_RUN_NUMBER --build-arg=token=$BUILD_TOKEN --no-cache
      -
        name: Push Docker image to DockerHub
        run:
          docker push $DOCKER_REPOSITORY/mock_gallery:$GITHUB_RUN_NUMBER
